### 1.[Error](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error) 分类

1. Error
2. InternalError
3. EvalError
4. RangeError
5. ReferenceError
6. SyntaxError
7. TypeError
8. URIError

1.自定义错误类型

```javascript
class CustomError extends Error {
  constructor(message) {
  	super(message);
    this.name = "CustomError";
      this.message = message;
    }
}
```



### 2.throw抛出错误

与try/catch 语句对应的一个机制是throw 操作符，用于在任何时候抛出自定义错误。使用throw 操作符时，代码立即停止执行，除非try/catch 语句捕获了抛出的值。

1.何时抛出错误

> 有些错误浏览器抛出信息模糊，需要明确定义。否则如果是一个复杂的Web 应用程序，有几千行JavaScript 代码，想要找到错误的原因就会很难。

```javascript
if (!(values instanceof Array)){
	throw new Error("process(): Argument must be an array.");
}
```

实际编写JavaScript 代码时，应该仔细评估每个函数，以及可能导致它们失败的情形。良好的错误处理协议可以保证只会发生你自己抛出的错误。

### 3.捕获错误

#### [1.try...catch...finally](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch)

1.For `try...catch` to work, the code must be runnable.  it should be valid JavaScript.It won’t work if the code is syntactically wrong, for instance it has unmatched curly braces:

```javascript
try {
  {{{{{{{{{{{{
} catch (err) {
  alert("The engine can't understand this code, it's invalid");
}
```

The JavaScript engine first reads the code, and then runs it. The errors that occur on the reading phase are called “parse-time” errors and are unrecoverable (from inside that code). That’s because the engine can’t understand the code.

只能捕获运行时错误，解析时的语法错误无法捕获。

**So, `try...catch` can only handle errors that occur in valid code.** Such errors are called “runtime errors” or, sometimes, “exceptions”.

2.`try...catch` **works synchronously**

只能捕获同步错误。



[1]: https://javascript.info/try-catch



#### 2.window.onerror

任何没有被try/catch 语句处理的错误都会在window 对象上触发error 事件。

```javascript
//错误消息、发生错误的URL 和行号
window.onerror = (message, url, line) => {
  console.log(message);
  return false;
};
```

> 在任何错误发生时，无论是否是浏览器生成的，都会触发error 事件并执行这个事件处理程序。然后，浏览器的默认行为就会生效，像往常一样显示这条错误消息。可以返回**false** 来阻止浏览器默认报告错误的行为。
>
> 通过返回false，这个函数实际上就变成了整个文档的try/catch 语句，**可以捕获所有未处理的*运行时错误***。这个事件处理程序应该是处理浏览器报告错误的最后一道防线。

1.跨域捕获

window.onerror 无法捕获跨域之后的异常信息, 需要给script 脚本设置跨域。

There are three levels of cross-origin access:

1. **No `crossorigin` attribute** – access prohibited.
2. **`crossorigin="anonymous"`** – access allowed if the server responds with the header `Access-Control-Allow-Origin` with `*` or our origin. Browser does not send authorization information and cookies to remote server.
3. **`crossorigin="use-credentials"`** – access allowed if the server sends back the header `Access-Control-Allow-Origin` with our origin and `Access-Control-Allow-Credentials: true`. Browser sends authorization information and cookies to remote server.

```html
<script>
window.onerror = function(message, url, line, col, errorObj) {
  alert(`${message}\n${url}, ${line}:${col}`);
};
</script>
<script crossorigin="anonymous" src="https://cors.javascript.info/article/onload-onerror/crossorigin/error.js"></script>
```

2.window.onerror 不会捕获promise的异常错误信息

3.webpack 压缩包 bundle.js 捕获

因为压缩文件原因，代码都在一行显示，错误信息也在一行，很不方便。解决方法：在webpack中开启source-map功能。在压缩文件末尾会有`*//# sourceMappingURL=bundle.js.map*`这样的注释。能拿到source-map 源文件。**交给中间层node去解析源文件，然后解析map文件后将数据传递给后台服务器。**（因为前端解析速度较慢，推荐服务器解析）。

> 需要注意如果应用访问量很大，上报时可进行信息过滤和采样等。

https://juejin.cn/post/6844903582672650253#heading-4

#### 3.Error handing with promise

https://javascript.info/promise-error-handling





